# Production Configuration for S.C.O.U.T. Platform Kubernetes Deployment
apiVersion: v1
kind: Namespace
metadata:
  name: scout-platform
  labels:
    name: scout-platform
    environment: production
    project: scout-platform
  annotations:
    description: "S.C.O.U.T. AI Talent Acquisition Platform Namespace"

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: scout-config
  namespace: scout-platform
  labels:
    app: scout-platform
    component: config
data:
  # Database Configuration
  db-host: "scout-postgres-service"
  db-port: "5432"
  db-name: "scout_platform"
  db-pool-size: "20"
  db-max-overflow: "30"
  db-pool-timeout: "30"
  db-pool-recycle: "3600"
  
  # Redis Configuration  
  redis-host: "scout-redis-service"
  redis-port: "6379"
  redis-db: "0"
  redis-ssl: "true"
  redis-socket-timeout: "5"
  redis-socket-connect-timeout: "5"
  redis-max-connections: "50"
  
  # Application Configuration
  app-name: "S.C.O.U.T. Platform"
  app-version: "1.0.0"
  app-description: "AI-Driven Talent Acquisition Platform"
  api-prefix: "/api/v1"
  docs-url: "/docs"
  
  # Security Configuration
  cors-origins: "https://scout-platform.com,https://app.scout-platform.com"
  cors-allow-credentials: "true"
  cors-allow-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  cors-allow-headers: "Content-Type,Authorization,X-Requested-With,Accept,Origin"
  
  # JWT Configuration
  algorithm: "HS256"
  access-token-expire-minutes: "30"
  refresh-token-expire-days: "7"
  remember-me-expire-days: "30"
  token-issuer: "scout-platform.com"
  token-audience: "scout-platform-api"
  
  # Rate Limiting Configuration
  rate-limit-per-minute: "60"
  rate-limit-burst: "10"
  max-login-attempts-per-email: "5"
  max-login-attempts-per-ip: "10"
  login-attempt-lockout-duration: "900"
  
  # Password Policy
  min-password-length: "8"
  max-password-length: "128"
  require-uppercase: "true"
  require-numbers: "true"
  require-special-chars: "true"
  password-history-count: "5"
  
  # Monitoring Configuration
  metrics-enabled: "true"
  health-check-interval: "30"
  log-level: "INFO"
  log-format: "json"
  
  # Feature Flags
  enable-registration: "true"
  enable-email-verification: "true"
  enable-2fa: "true"
  enable-audit-logging: "true"
  enable-rate-limiting: "true"
  
  # Azure OpenAI Configuration
  azure-openai-deployment: "gpt-4"
  azure-openai-version: "2024-02-15-preview"
  azure-openai-max-tokens: "4096"
  azure-openai-temperature: "0.7"
  
  # Pinecone Configuration
  pinecone-environment: "production"
  pinecone-index-name: "scout-platform"
  pinecone-dimension: "1536"
  pinecone-metric: "cosine"

---
# Enhanced Secret template (values should be set via external secret management)
apiVersion: v1
kind: Secret
metadata:
  name: scout-secrets
  namespace: scout-platform
  labels:
    app: scout-platform
    component: secrets
type: Opaque
stringData:
  # Database
  database-url: "postgresql://username:password@scout-postgres-service:5432/scout_platform"
  
  # Redis
  redis-url: "rediss://username:password@scout-redis-service:6379/0"
  
  # JWT & Encryption
  jwt-secret: "your-super-secret-jwt-key-change-in-production"
  encryption-key: "your-32-character-encryption-key-here"
  
  # Azure OpenAI
  azure-openai-api-key: "your-azure-openai-api-key"
  azure-openai-endpoint: "https://your-resource.openai.azure.com/"
  
  # Pinecone
  pinecone-api-key: "your-pinecone-api-key"
  
  # Email Service (SendGrid)
  sendgrid-api-key: "your-sendgrid-api-key"
  
  # Monitoring & Observability
  sentry-dsn: "https://your-sentry-dsn@sentry.io/project-id"
  datadog-api-key: "your-datadog-api-key"
  
  # Cloud Storage
  azure-storage-account-name: "your-storage-account"
  azure-storage-account-key: "your-storage-account-key"
  azure-storage-container: "scout-platform-uploads"

---
# Resource Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scout-platform-quota
  namespace: scout-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    requests.storage: 50Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"

---
# Limit Ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: scout-platform-limits
  namespace: scout-platform
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: "256Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
      ephemeral-storage: "4Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    type: Container

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scout-config
  namespace: scout-platform
data:
  DEBUG: "false"
  CORS_ORIGINS: "https://app.scout-platform.com"
  ALLOWED_HOSTS: "scout-platform.com,api.scout-platform.com"
  RATE_LIMIT_PER_MINUTE: "100"
  RATE_LIMIT_BURST: "200"